### PR TITLE
Use proper HTTP verbs and REST-like URIs for API endpoints

### PR DESCRIPTION
**Pull request by timofurrer**
I propose to use the "correct" HTTP verbs and a resource based URI scheme for the backend API endpoints. With doing so the backend API also appeals REST-fanatics :tada:

### CODE REVIEW

**Comment by fliiiix** [comment]
Good shit

**Comment by fliiiix** [comment]
btw. I allowed POST by design for broken clients which only do GET and POST

**Comment by timofurrer** [comment]
broken clients? Don't use them. Out of curiosity: which considerable tool doesn't allow to send PUT?

**Comment by fliiiix** [comment]
HTML Forms for example

**Comment by randombenj** [comment]
Awesome!

**Pull request merged**
